server:
  port: 8084

spring:
  application:
    name: ms-analisis-experiencia
  profiles:
    active: dev

  autoconfigure:
    exclude:
      - org.springdoc.core.configuration.SpringDocHateoasConfiguration

  datasource:
    url: jdbc:mysql://localhost:3306/db_experiencia?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: mi_clave_secreta_muy_larga_para_la_perfumeria_2026
  expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true