server:
  port: 8761

spring:
  application:
    name: ms-eureka-server

eureka:
  instance:
    hostname: localhost
#  server:
    # DESACTIVA EL MODO DE PÁNICO EN LOCAL
 #   enable-self-preservation: false
 #   eviction-interval-timer-in-ms: 2000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/