spring.application.name=ms-tienda-oferta
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/db_tienda?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secret=mi_clave_secreta_muy_larga_para_la_perfumeria_2026
jwt.expiration=86400000

ms.catalogo.url=http://localhost:8082
ms.usuario.url=http://localhost:8081